-- AlterTable
ALTER TABLE "JournalEntry" ALTER COLUMN "mood" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "stress" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "energy" SET DATA TYPE DOUBLE PRECISION;
